### ISSUE TITLE
VLC Button not showing

### ISSUE THREAD

**Issue by nigelwarning** [soerenkampschroer/plex-to-vlc#26]
Hello,

I have a Macbook Air 2020 M1 Apple Silicon version and the vlc button is not showing.

Chrome version:
Versie 91.0.4472.114 (Officiële build) (arm64

Plex to VLC version:
1.3

Mac Operating:
Big sur 11.4

Plex version:
1.23.3.4706

**Comment by frosty00** [comment]
Same here

**Comment by soerenkampschroer** [comment]
@nigelwarning @frosty00 Thanks for letting me know! I honestly haven't been using Plex for a long time now so I didn't know they did a redesign. I've updated the extension and the bug is fixed. Google wants to review my extension though as it hasn't been updated in quite some time. They say it can take several weeks to be published but I hope they get to it sooner. The changes I've made are in the repo, so if you want you can load the extension yourself until the new version hits the store. If you need help with that just let me know.

Anyways thank you for reporting the bug and if you'd like leave a review in the store ;)
